apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
  namespace: first-app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: IMG
        resources:
          limits:
            memory: 128M
            cpu: "500m"
        ports:
        - containerPort: 8080
