name: 'Develop'

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ASSUME_ROLE: ${{ vars.AWS_ASSUME_ROLE }}
  REPOSITORY_NAME: ${{ github.event.repository.name }}
  BUCKET_CODE: ${{ vars.BUCKET_CODE }}
  ENVIRONMENT: "dev"

jobs:
  # Build the code
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      id: maven-build
      working-directory: app
      run: |
        mvn -B package --file pom.xml

    - run: |
        echo "Current folder"
        pwd
        echo "Listing files"
        ls
        echo "Creating folder artifacts"
        mkdir artifacts
        echo "Copying jar"
        cp app/target/*.jar artifacts/app.jar
        echo "Listing files"
        ls artifacts

    - name: Uploading artifacts
      uses: actions/upload-artifact@master
      with:
        name: app.jar
        path: artifacts

  build-image:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@master
        with:
          name: app.jar
          path: artifacts

      - name: Copy artifact
        run: cp artifacts/app.jar app/app.jar

      - name: Build the Docker image
        working-directory: app
        run: docker build . --file Dockerfile -t $REPOSITORY_NAME

      # Configure aws credentials with assumerole
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github_actions_oidc_role

      - name: Docker login ECR
        run: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com

      - name: Push Docker Image ECR
        id: push-image
        working-directory: app
        run: |
          DOCKER_TAG=$(date +%s)
          docker tag app-java-k8s-template:latest $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/$REPOSITORY_NAME:$DOCKER_TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/$REPOSITORY_NAME:$DOCKER_TAG
          echo "docker_image=$REPOSITORY_NAME:$DOCKER_TAG" >> $GITHUB_OUTPUT

    outputs:
      docker_image: ${{ steps.push-image.outputs.docker_image }}

  scan-image:
    runs-on: ubuntu-latest
    #needs: build-image
    env:
      IMAGE_NAME: ${{ needs.build-image.outputs.docker_image }}

    steps:
      - uses: actions/checkout@v3

      # Configure aws credentials with assumerole
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github_actions_oidc_role

      - name: Docker login ECR
        run: aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com

      #- name: Pull image
      #  run: |
      #    echo "Pulling image $IMAGE_NAME"
      #    docker pull $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/$IMAGE_NAME
      #    echo "saving image"
      #    docker save -o vuln-image.tar $IMAGE_NAME
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '$AWS_ACCOUNT_ID.dkr.ecr.region.amazonaws.com/$REPOSITORY_NAME:1699801925'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: $AWS_ACCOUNT_ID.dkr.ecr.sa-east-1.amazonaws.com/$$REPOSITORY_NAME:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  #deploy-k8s:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #
  #    # Configure aws credentials with assumerole
  #    - name: Configure AWS Credentials
  #      uses: aws-actions/configure-aws-credentials@v3
  #      with:
  #        role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
  #        aws-region: ${{ env.AWS_REGION }}
  #        role-session-name: github_actions_oidc_role
  #
  #   - name: Deploy Kubernetes
  #      working-directory: infra
  #      run: kubectl apply -f .